### ISSUE TITLE
Too many errors of type "Access denied" 

### ISSUE THREAD

**Issue by LinaYorda** [soxoj/maigret#1166]
Hi soxoj, thanks for the handy tool. I installed the Margret from the sources but continue getting this permission error. Steps I took so far that didnt help:

1. git pull
2. permission change of the /usr/.local/share//tools/maigret/maigret/resources/data.json

I would appreciate your help. 

----------------------------------------------------------------------------------------------------------------------------------

[-] Restarting checks for 5 sites... (1 attempts left)
100%|████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:30<00:00,  6.10s/it]
[!] Too many errors of type "Access denied" (4.0%)
[-] You can see detailed site check errors with a flag `--print-errors`
[*] Short text report:
Search by username sfenliva returned 15 accounts.
Extended info extracted from 1 accounts.
Countries: in, us, ru, ca, by, eu
Interests (tags): coding, sharing, art, photo, tech, gaming, video, stock
Traceback (most recent call last):
  File "/usr/share/maigret/maigret.py", line 21, in <module>
    run()
  File "/usr/share/maigret/maigret.py", line 11, in run
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/maigret/maigret/maigret.py", line 727, in main
    db.save_to_file(db_file)
  File "/usr/share/maigret/maigret/sites.py", line 304, in save_to_file
    with open(filename, "w") as f:
         ^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/share/maigret/maigret/resources/data.json'

**Comment by Laura7089** [comment]
Think you're having the same problem as #678

**Comment by soxoj** [comment]
Thanks, I'll fix it soon.
