### ISSUE TITLE
TypeError: Object of type MaigretSite is not JSON serializable

### ISSUE THREAD

**Issue by maximousblk** [soxoj/maigret#120]
error:
![image](https://user-images.githubusercontent.com/28438021/116814426-8c1af680-ab76-11eb-8e6e-33743fc69427.png)

<details>
<summary>text</summary>

```red
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.4/x64/bin/maigret", line 33, in <module>
    sys.exit(load_entry_point('maigret==0.1.20', 'console_scripts', 'maigret')())
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/maigret/maigret.py", line 617, in run
    loop.run_until_complete(main())
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/maigret/maigret.py", line 588, in main
    save_json_report(filename, username, results, report_type=args.json)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/maigret/report.py", line 71, in save_json_report
    generate_json_report(username, results, f, report_type=report_type)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/maigret/report.py", line 280, in generate_json_report
    file.write(json.dumps(all_json))
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MaigretSite is not JSON serializable
Error: Process completed with exit code 1.
```

</details>

using latest commit: https://github.com/soxoj/maigret/commit/1afdda7336b100522a4ce452b79ef9f2ba2fe19a

**Comment by soxoj** [comment]
Thank you, is this error reproducible for json report only?

**Comment by soxoj** [comment]
I fixed the bug, made tests to avoid such errors in the future, and published a new version. Please, check.

**Comment by maximousblk** [comment]
yes this is fixed now
