### ISSUE TITLE
xhtmp2pdf error with Win32 standalone binary

### ISSUE THREAD

**Issue by soxoj** [soxoj/maigret#208]
Crashing while generating PDF report
```
Traceback (most recent call last):
  File "maigret_standalone.py", line 7, in <module>
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 579, in run_until_complete
  File "maigret\maigret.py", line 696, in main
  File "maigret\report.py", line 79, in save_pdf_report
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "xhtml2pdf\pisa.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "xhtml2pdf\default.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "xhtml2pdf\util.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "arabic_reshaper\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "arabic_reshaper\arabic_reshaper.py", line 242, in <module>
  File "arabic_reshaper\arabic_reshaper.py", line 64, in __init__
  File "arabic_reshaper\reshaper_config.py", line 44, in auto_config
Exception: Default configuration file C:\Users\User\AppData\Local\Temp\_MEI2216
\arabic_reshaper\default-config.ini not found, check the module installation.
[8872] Failed to execute script 'maigret_standalone' due to unhandled exception

```

**Comment by soxoj** [comment]
Check https://github.com/mpcabd/python-arabic-reshaper/issues/12
