### ISSUE TITLE
pyvis error with Win32 standalone binary

### ISSUE THREAD

**Issue by soxoj** [soxoj/maigret#209]
Crashing while generating graph report
```
Traceback (most recent call last):
  File "maigret_standalone.py", line 7, in <module>
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 579, in run_until_complete
  File "maigret\maigret.py", line 701, in main
  File "maigret\report.py", line 210, in save_graph_report
  File "pyvis\network.py", line 74, in __init__
  File "pyvis\network.py", line 498, in prep_notebook
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppDat
a\\Local\\Temp\\_MEI83082\\pyvis/templates/template.html'
[6996] Failed to execute script 'maigret_standalone' due to unhandled exception!

```

**Comment by MaxFinken** [comment]
Hey, how did you fix this issue?
