### ISSUE TITLE
false positive in TikTok

### ISSUE THREAD

**Issue by ManuelQ59** [soxoj/maigret#307]
hello, I have verified that you are giving false positive on TikTok, you are falsifying active users on tiktok. Check it please, thank you

**Comment by soxoj** [comment]
Hey, did you check the actual version from master? I fixed a TikTok false positive 3 hours ago.
If you observe a false positive for the last version of Maigret, please give me an example.

**Comment by ManuelQ59** [comment]
I will check and write again, thanks :)

**Comment by soxoj** [comment]
I close the issue, will reopen if you find out a problem

**Comment by ManuelQ59** [comment]
Hello, good morning, I have updated the tool, and I have searched for a user and it continues to give me false negatives, what I could see is in Tik Tok. Example: I put the user to search for "@nicollekaqui", and it tells me that he does not have a TIKTOK account (invalid?), but when verifying, that user does have a TIKTOK account (https://www.tiktok.com /@nicollekaqui), you can see that it is a public account. I hope they can correct. Thanks

**Comment by soxoj** [comment]
Thank you. I'll rename the issue cause it is a false negative, not a false positive. 
Unfortunately, I am unable to reproduce this behavior for some reason.

Please, attach full debug logs, this information will be invaluable.
`./maigret.py nicollekaqui --site TikTok -d 2> log.txt 1>&2`

The logfile will contain your IP address, you can censor it manually before attaching the file.

**Comment by ManuelQ59** [comment]
[-] Starting a search on top 2 sites from the Maigret database...
[!] You can run search by full list of sites with flag `-a`
[*] Checking username nicollekaqui on:
Traceback (most recent call last):
  File "/home/XXX/TOOLS/maigret/./maigret.py", line 18, in <module>
    run()
  File "/home/XXX/TOOLS/maigret/./maigret.py", line 11, in run
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/XXX/TOOLS/maigret/maigret/maigret.py", line 627, in main
    results = await maigret(
  File "/home/XXX/TOOLS/maigret/maigret/checking.py", line 631, in maigret
    clearweb_checker = SimpleAiohttpChecker(
  File "/home/XXX/TOOLS/maigret/maigret/checking.py", line 64, in __init__
    from aiohttp_socks import ProxyConnector
  File "/usr/local/lib/python3.9/dist-packages/aiohttp_socks/__init__.py", line 5, in <module>
    from .connector import (
  File "/usr/local/lib/python3.9/dist-packages/aiohttp_socks/connector.py", line 8, in <module>
    from aiohttp.helpers import CeilTimeout  # noqa
ImportError: cannot import name 'CeilTimeout' from 'aiohttp.helpers' (/usr/lib/python3/dist-packages/aiohttp/helpers.py)

**Comment by soxoj** [comment]
Looks like another issue. Have you seen this before? 
Please, attach only logfile requested above from the working version of Maigret.

**Comment by ManuelQ59** [comment]
🙄

**Comment by ManuelQ59** [comment]
[https://github.com/ManuelQ59/CompilationOfManyBreaches/blob/main/log.txt](url)

**Comment by ManuelQ59** [comment]
[log.txt](https://github.com/soxoj/maigret/files/7905300/log.txt)

**Comment by soxoj** [comment]
Please, try to install [this version](https://github.com/soxoj/maigret/archive/refs/heads/aiohttp-error-fix.zip) with a fix.

**Comment by soxoj** [comment]
@ManuelQ59, check, please

**Comment by ManuelQ59** [comment]
Okay, I'll do tests as soon as I get unoccupied, since I'm working on a project.

**Comment by ManuelQ59** [comment]
> ./maigret.py nicollekaqui
![maigret](https://user-images.githubusercontent.com/89365972/150696945-0b6be03a-c0ea-48fc-8a1e-79a94874f1d4.PNG)

**Comment by ManuelQ59** [comment]
![image](https://user-images.githubusercontent.com/89365972/150697150-94507ca2-6480-465a-a7c0-587df2e5b64f.png)

**Comment by soxoj** [comment]
Please, attach only logfile requested above.
