### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by zl9801** [soxoj/maigret#581]
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021998DC95A0>
Traceback (most recent call last):
  File "D:\Program Files\python\python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Program Files\python\python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Program Files\python\python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "D:\Program Files\python\python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by zl9801** [comment]
Twitter username not found.
What's wrong.

PS D:\file_split\temp\maigret> maigret volcano9801 --site Twitter -a --i2p-proxy http://127.0.0.1:10809 --html
[-] Starting a search on top 2 sites from the Maigret database...
[*] Checking username volcano9801 on:
100%|██████████████████████████████████████████████████████████████████| 2/2 [00:21<00:00, 10.51s/it]
[-] Restarting checks for 2 sites... (1 attempts left)
100%|██████████████████████████████████████████████████████████████████| 2/2 [00:21<00:00, 10.51s/it]
[!] Too many errors of type "Connecting failure" (100.0%)
[-] You can see detailed site check errors with a flag `--print-errors`
[-] Generating report info...
[-] HTML report on all usernames saved in D:\file_split\temp\maigret\reports\report_volcano9801_plain.html
[*] Short text report:
Search by username volcano9801 returned 0 accounts.
Extended info extracted from 0 accounts.

**Comment by fen0s** [comment]
you have connection failure errors, so it might be:
1) your proxy not working properly
2) your proxy's host being located in RU, where twitter is blocked
have you checked those as reasons for your issue?

**Comment by soxoj** [comment]
Thank you for your report, we will fix Twitter in the near future

**Comment by soxoj** [comment]
**There are some issues with sockets, as connection failures occur when the number of threads is low.**

How to reproduce: `maigret soxoj --retries 0 -n 10 --top-sites 500 --no-extracting --no-recursion --timeout 5 -v`
```
[!] Too many errors of type "Connecting failure" (54.0%). Try to decrease number of parallel connections (e.g. -n 10)
[!] Too many errors of type "Access denied" (3.0%)
[-] Verbose error statistics:
[!] Connecting failure: 54.0%
[!] Access denied: 3.0%
[!] Request timeout: 1.0%
[!] Site-specific: 0.0%
[!] Unexpected: 0.0%
[!] Request failed: 0.0%
[!] Server: 0.0%
[!] Unsupported username format: 0.0%
```

**Comment by soxoj** [comment]
It should be fixed now in the main branch version (not published in Pypi yet).
@zl9801 please, check!
