### ISSUE TITLE
Attempt to write into Python distribution folders

### ISSUE THREAD

**Issue by ArneBachmann** [soxoj/maigret#678]
After a successful run of maigret with many matches I get this error:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/maigret", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/maigret/maigret.py", line 723, in run
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/maigret/maigret.py", line 717, in main
    db.save_to_file(db_file)
  File "/usr/local/lib/python3.10/dist-packages/maigret/sites.py", line 304, in save_to_file
    with open(filename, "w") as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/maigret/resources/data.json'
```

Obviously maigret should not attempt to write into a Python-internal folder.

**Comment by soxoj** [comment]
Thanks, it is known bug, we were going to use home folder for saving local updates of the Maigret DB.

**Comment by soxoj** [comment]
Should be fixed.
