### ISSUE TITLE
ValueError: too many file descriptors in select()

### ISSUE THREAD

**Issue by Nambers** [soxoj/maigret#718]
## Checklist

- [x] I'm reporting a bug in Maigret functionality
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

Info about Maigret version you are running and environment (`--version`, operation system, ISP provider):
<INSERT VERSION INFO HERE>

```
system = windows 11 pro, bit 64
exe_file = maigret_standalone.exe
version = {
maigret_standalone 0.4.4
Socid-extractor:  0.0.23
Aiohttp:  3.8.1
Requests:  2.28.1
Python:  3.7.5
}
```

How to reproduce this bug (commandline options / conditions):

command:
`maigret_standalone "<name_a>" "<name_b>" "<name_c>" "<name_d>" "<name_e>" --top-sites 500 --html`

```
 90%|███████████████████████████████████████████████████████████████████████▊        | 449/500 [00:16<00:00, 57.60it/s]Traceback (most recent call last):
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 566, in run_until_complete
  File "asyncio\base_events.py", line 534, in run_forever
  File "asyncio\base_events.py", line 1735, in _run_once
  File "selectors.py", line 323, in select
  File "selectors.py", line 314, in _select
ValueError: too many file descriptors in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "maigret_standalone.py", line 7, in <module>
  File "asyncio\runners.py", line 46, in run
  File "asyncio\runners.py", line 62, in _cancel_all_tasks
  File "asyncio\base_events.py", line 566, in run_until_complete
  File "asyncio\base_events.py", line 534, in run_forever
  File "asyncio\base_events.py", line 1735, in _run_once
  File "selectors.py", line 323, in select
  File "selectors.py", line 314, in _select
ValueError: too many file descriptors in select()
[23716] Failed to execute script 'maigret_standalone' due to unhandled exception!
```
Is that because I run win32 maigret_standalone.exe in 64bit windows?

**Comment by soxoj** [comment]
Hey, thank you for the report!

I think the problem in a number of simultaneous http requests, could you try to decrease count of parallel connections with `-n` flag and check if problem disappear?

**Comment by Nambers** [comment]
> Hey, thank you for the report!
> 
> I think the problem in a number of simultaneous http requests, could you try to decrease count of parallel connections with `-n` flag and check if problem disappear?

How many connections is appropriate?
I use it in a Windows 11 machine with i7-11370H

**Comment by Nambers** [comment]
`-n 10` works for me
