### ISSUE TITLE
Google Cloud Shell exceptions

### ISSUE THREAD

**Issue by soxoj** [soxoj/maigret#74]
```
[base_events.py:1608] ERROR  21:18:01 SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f916014df60>
transport: <_SelectorSocketTransport fd=191 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609
```

```$ ./maigret.py --version
maigret.py 0.1.15
Socid-extractor:  0.0.13
Aiohttp:  3.7.4
Requests:  2.25.1
Python:  3.7.3
```

**Comment by soxoj** [comment]
```
[base_events.py:1608] ERROR  21:09:33 SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f9eb87c5da0>
transport: <_SelectorSocketTransport closing fd=522 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)```

**Comment by soxoj** [comment]
Close the issue, no longer reproducible.
